platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'AppDemo' do
  # Core
  pod 'ReactiveObjC', '3.1.1'
  pod 'YYKit', '1.0.9'
  pod 'Masonry', '1.1.0'
  pod 'SDAutoLayout', '2.2.1'
  pod 'YTKNetwork', '3.0.6'
  pod 'FMDB', '2.7.5'
  pod 'pop', '1.0.12'

  # UI_Component
  pod 'MJRefresh', '3.7.2'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'TABAnimated', '2.6.0'
  pod 'ChameleonFramework', '2.1.0'
  pod 'XHLaunchAd', '3.9.12'
  pod 'CWLateralSlide', '1.6.5'
  pod 'SVProgressHUD', '2.2.5'
  pod 'IQKeyboardManager', '6.5.6'
  pod 'NYSTK', '0.0.8'
  pod 'WMZBanner', '1.2.0'
  pod 'SGPagingView', '1.7.2'
  pod 'BRPickerView', '2.7.3'
  pod 'TXScrollLabelView', '1.3.2'
  pod 'SGQRCode', '3.5.1'
  pod 'TZImagePickerController'
  pod 'JXCategoryView'
  pod 'JXPagingView/Pager'
  
#  pod 'MSNumberScrollAnimatedView'
#  pod 'XRWaterfallLayout'
#  pod 'XHInputView'
#  pod 'KNPhotoBrowser'
#  pod 'ActionSheetPicker-3.0'
#  pod 'CRBoxInputView'

  # Third_Platform
  pod 'JPush', '3.7.4'
  pod 'RongCloudIM', '5.1.4.1'
#  pod 'RongCloudRTC'
#  pod 'RongCloudRTC/RongCallLib'
  pod 'UMCCommon'
  pod 'UMCCommonLog', '2.0.2'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/ReducedWeChat'
  pod 'UMengUShare/Social/ReducedQQ'
end
