platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'AppDemo' do
  # Core
  pod 'ReactiveObjC'
  pod 'Masonry'
  pod 'YYKit'
  pod 'SDAutoLayout'
  pod 'YTKNetwork'
  pod 'FMDB'
  pod 'pop'
  #  pod 'AsyncDisplayKit', '2.2'

  # UI_Component
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'XHLaunchAd'
  pod 'NYSTK', '0.0.8'
  pod 'BRPickerView'
  pod 'JXCategoryView'
  pod 'JXPagingView/Pager'
#  pod 'SGPagingView'
#  pod 'AXWebViewController'
#  pod 'WMZBanner'
#  pod 'TXScrollLabelView', '1.3.2'
#  pod 'MSNumberScrollAnimatedView'
#  pod 'XRWaterfallLayout'
#  pod 'XHInputView'
#  pod 'KNPhotoBrowser'
#  pod 'TZImagePickerController'
#  pod 'ActionSheetPicker-3.0'
#  pod 'CRBoxInputView'

  # Third_Platform
  pod 'JPush'
  pod 'RongCloudIM'
#  pod 'RongCloudRTC/RongCallLib'
  pod 'UMCCommon'
  pod 'UMCCommonLog'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/ReducedWeChat'
#  pod 'UMengUShare/Social/ReducedQQ'
#  pod 'UMengUShare/Social/ReducedSina‘
end
